test:
  image: elixir:1.7.4
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: unshortener_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
    MIX_ENV: "test"
  script:
    - mix local.rebar --force
    - mix local.hex --force
    - apt-get update && apt-get -y install postgresql-client
    - mix deps.get
    - mix format --check-formatted
    - mix ecto.create
    - mix ecto.migrate
    - mix coveralls

build-docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
